"""renta fija directa

Revision ID: 02f00629aa63
Revises: 4109be027d7a
Create Date: 2026-09-20 23:59:17.914809
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# Autogenerate renderiza las columnas monetarias como app.db.types.ExactNumeric
# y las de fecha como app.db.types.UtcDateTime, pero NO añade este import por
# su cuenta. Sin él, cualquier migración que toque esas columnas falla con
# NameError al ejecutarse.
import app.db.types  # noqa: F401

# El variant JSONB de PostgreSQL se renderiza como
# postgresql.JSONB(astext_type=Text()), con Text sin cualificar.
from sqlalchemy import Text  # noqa: F401


revision: str = '02f00629aa63'
down_revision: str | None = '4109be027d7a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixed_income_terms',
    sa.Column('id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), nullable=False),
    sa.Column('asset_id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), nullable=False),
    sa.Column('issuer', sa.String(length=120), nullable=False),
    sa.Column('rate_kind', sa.Enum('FIXED', 'IBR', 'DTF', 'UVR', 'IPC', name='rate_kind', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('annual_rate_pct', app.db.types.ExactNumeric(precision=9, scale=4), nullable=False),
    sa.Column('issued_on', sa.Date(), nullable=False),
    sa.Column('matures_on', sa.Date(), nullable=False),
    sa.Column('has_secondary_market', sa.Boolean(), nullable=False),
    sa.Column('withholding_pct', app.db.types.ExactNumeric(precision=9, scale=4), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('created_at', app.db.types.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('CAST(annual_rate_pct AS NUMERIC) > -100', name=op.f('ck_fixed_income_terms_annual_rate_sane')),
    sa.CheckConstraint('matures_on > issued_on', name=op.f('ck_fixed_income_terms_matures_after_issue')),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_fixed_income_terms_asset_id_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fixed_income_terms'))
    )
    with op.batch_alter_table("fixed_income_terms", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_fixed_income_terms_asset_id"), ["asset_id"], unique=True
        )

    _ampliar_check_de_asset_type(_TIPOS_NUEVOS)


# El CHECK de `assets.asset_type` hay que tocarlo A MANO.
#
# `app/db/alembic_support.py` filtra los CHECK que generan los Enum, porque si
# no autogenerate produciría una migración espuria que los borraría en cada
# revisión. El precio de esa decisión es este: añadir un valor al enum no se
# detecta solo, y sin esto la base rechazaría la primera fila FIXED_INCOME con
# un IntegrityError que no dice qué pasó.
_TIPOS_VIEJOS = ("STOCK", "ETF", "ADR", "REIT", "FUND", "CRYPTO", "OTHER")
_TIPOS_NUEVOS = (*_TIPOS_VIEJOS, "FIXED_INCOME")


def _ampliar_check_de_asset_type(tipos: tuple[str, ...]) -> None:
    valores = ", ".join(f"'{t}'" for t in tipos)
    with op.batch_alter_table("assets", schema=None) as batch_op:
        batch_op.drop_constraint("asset_type", type_="check")
        batch_op.create_check_constraint("asset_type", f"asset_type IN ({valores})")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _ampliar_check_de_asset_type(_TIPOS_VIEJOS)

    with op.batch_alter_table("fixed_income_terms", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fixed_income_terms_asset_id"))

    op.drop_table('fixed_income_terms')
    # ### end Alembic commands ###
