"""ingestion pipeline and price history storage

Revision ID: 320fcf27a88a
Revises: 4f70dcca1811
Create Date: 2026-08-30 19:35:41.427200
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# Autogenerate renderiza las columnas monetarias como app.db.types.ExactNumeric
# y las de fecha como app.db.types.UtcDateTime, pero NO añade este import por
# su cuenta. Sin él, cualquier migración que toque esas columnas falla con
# NameError al ejecutarse.
import app.db.types  # noqa: F401

# El variant JSONB de PostgreSQL se renderiza como
# postgresql.JSONB(astext_type=Text()), con Text sin cualificar.
from sqlalchemy import Text  # noqa: F401


revision: str = '320fcf27a88a'
down_revision: str | None = '4f70dcca1811'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), nullable=False),
    sa.Column('trigger', sa.Enum('SCHEDULED', 'MANUAL', 'STARTUP_CATCHUP', name='sync_trigger', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCESS', 'PARTIAL', 'FAILED', name='sync_status', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('started_at', app.db.types.UtcDateTime(), nullable=False),
    sa.Column('finished_at', app.db.types.UtcDateTime(), nullable=True),
    sa.Column('symbols_requested', sa.Integer(), nullable=False),
    sa.Column('symbols_failed', sa.Integer(), nullable=False),
    sa.Column('quotes_updated', sa.Integer(), nullable=False),
    sa.Column('bars_written', sa.Integer(), nullable=False),
    sa.Column('fundamentals_updated', sa.Integer(), nullable=False),
    sa.Column('fx_updated', sa.Integer(), nullable=False),
    sa.Column('metadata_updated', sa.Integer(), nullable=False),
    sa.Column('warnings', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_runs'))
    )
    with op.batch_alter_table('sync_runs', schema=None) as batch_op:
        batch_op.create_index('ix_sync_runs_started_at', ['started_at'], unique=False)

    # server_default es obligatorio: la columna es NOT NULL y las filas que ya
    # existen necesitan un valor. Se retira después para que el default viva en
    # el modelo, no en el esquema.
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('is_universe', sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.create_index(batch_op.f('ix_assets_is_universe'), ['is_universe'], unique=False)
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.alter_column('is_universe', server_default=None)

    # --- price_history: WITHOUT ROWID + poda de columnas ---------------------
    #
    # No se usa batch_alter_table: reconstruye la tabla a partir del esquema
    # REFLEJADO, así que arrastraría el rowid. Y `WITHOUT ROWID` no se puede
    # añadir con ALTER en ningún motor: exige recrear.
    #
    # Se copian los datos en lugar de re-descargarlos: son barras cerradas e
    # inmutables, y volver a bajarlas costaría cientos de llamadas al proveedor.
    op.create_table(
        'price_history_new',
        sa.Column('asset_id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('open', sa.Float(), nullable=True),
        sa.Column('high', sa.Float(), nullable=True),
        sa.Column('low', sa.Float(), nullable=True),
        sa.Column('close', sa.Float(), nullable=False),
        sa.Column('adj_close', sa.Float(), nullable=True),
        sa.Column('volume', sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ['asset_id'], ['assets.id'],
            name=op.f('fk_price_history_asset_id_assets'), ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('asset_id', 'date', name=op.f('pk_price_history')),
        sqlite_with_rowid=False,
    )
    op.execute(
        'INSERT INTO price_history_new '
        '(asset_id, date, open, high, low, close, adj_close, volume) '
        'SELECT asset_id, date, open, high, low, close, adj_close, volume '
        'FROM price_history'
    )
    op.drop_index('ix_price_history_date', table_name='price_history')
    op.drop_table('price_history')
    op.rename_table('price_history_new', 'price_history')
    op.create_index('ix_price_history_date', 'price_history', ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # price_history vuelve a tener rowid y las columnas de procedencia. Los
    # valores de source/fetched_at se reconstruyen con constantes: el dato
    # original por fila ya no existe, y por eso mismo se eliminó.
    op.create_table(
        'price_history_old',
        sa.Column('asset_id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('open', sa.Float(), nullable=True),
        sa.Column('high', sa.Float(), nullable=True),
        sa.Column('low', sa.Float(), nullable=True),
        sa.Column('close', sa.Float(), nullable=False),
        sa.Column('adj_close', sa.Float(), nullable=True),
        sa.Column('volume', sa.BigInteger(), nullable=True),
        sa.Column('source', sa.String(length=20), nullable=False, server_default='yfinance'),
        sa.Column('fetched_at', app.db.types.UtcDateTime(), nullable=False,
                  server_default=sa.text('(CURRENT_TIMESTAMP)')),
        sa.ForeignKeyConstraint(
            ['asset_id'], ['assets.id'],
            name=op.f('fk_price_history_asset_id_assets'), ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('asset_id', 'date', name=op.f('pk_price_history')),
    )
    op.execute(
        'INSERT INTO price_history_old '
        '(asset_id, date, open, high, low, close, adj_close, volume) '
        'SELECT asset_id, date, open, high, low, close, adj_close, volume '
        'FROM price_history'
    )
    op.drop_index('ix_price_history_date', table_name='price_history')
    op.drop_table('price_history')
    op.rename_table('price_history_old', 'price_history')
    op.create_index('ix_price_history_date', 'price_history', ['date'], unique=False)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_is_universe'))
        batch_op.drop_column('is_universe')

    with op.batch_alter_table('sync_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_sync_runs_started_at')

    op.drop_table('sync_runs')
    # ### end Alembic commands ###
