"""tasas de referencia de banrep

Revision ID: 4109be027d7a
Revises: 6fced7175482
Create Date: 2026-09-20 23:57:33.782473
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# Autogenerate renderiza las columnas monetarias como app.db.types.ExactNumeric
# y las de fecha como app.db.types.UtcDateTime, pero NO añade este import por
# su cuenta. Sin él, cualquier migración que toque esas columnas falla con
# NameError al ejecutarse.
import app.db.types  # noqa: F401

# El variant JSONB de PostgreSQL se renderiza como
# postgresql.JSONB(astext_type=Text()), con Text sin cualificar.
from sqlalchemy import Text  # noqa: F401


revision: str = '4109be027d7a'
down_revision: str | None = '6fced7175482'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reference_rates',
    sa.Column('id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), nullable=False),
    sa.Column('series', sa.String(length=40), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=8), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('fetched_at', app.db.types.UtcDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reference_rates')),
    sa.UniqueConstraint('series', 'as_of', name='uq_reference_rate_series_date')
    )
    with op.batch_alter_table('reference_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reference_rates_series'), ['series'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reference_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reference_rates_series'))

    op.drop_table('reference_rates')
    # ### end Alembic commands ###
