"""plan de asignacion entre clases

Revision ID: 4dc3014a8333
Revises: 5f3b6de5e33d
Create Date: 2026-09-20 23:47:39.617719
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# Autogenerate renderiza las columnas monetarias como app.db.types.ExactNumeric
# y las de fecha como app.db.types.UtcDateTime, pero NO añade este import por
# su cuenta. Sin él, cualquier migración que toque esas columnas falla con
# NameError al ejecutarse.
import app.db.types  # noqa: F401

# El variant JSONB de PostgreSQL se renderiza como
# postgresql.JSONB(astext_type=Text()), con Text sin cualificar.
from sqlalchemy import Text  # noqa: F401


revision: str = '4dc3014a8333'
down_revision: str | None = '5f3b6de5e33d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allocation_targets',
    sa.Column('id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), nullable=False),
    sa.Column('portfolio_id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), nullable=False),
    sa.Column('asset_class', sa.String(length=32), nullable=False),
    sa.Column('target_pct', app.db.types.ExactNumeric(precision=6, scale=2), nullable=False),
    sa.Column('band_pct', app.db.types.ExactNumeric(precision=6, scale=2), nullable=False),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('created_at', app.db.types.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('CAST(band_pct AS NUMERIC) >= 0 AND CAST(band_pct AS NUMERIC) <= 100', name=op.f('ck_allocation_targets_band_pct_range')),
    sa.CheckConstraint('CAST(target_pct AS NUMERIC) >= 0 AND CAST(target_pct AS NUMERIC) <= 100', name=op.f('ck_allocation_targets_target_pct_range')),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_allocation_targets_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_allocation_targets')),
    sa.UniqueConstraint('portfolio_id', 'asset_class', name='uq_allocation_portfolio_class')
    )
    with op.batch_alter_table('allocation_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allocation_targets_portfolio_id'), ['portfolio_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allocation_targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allocation_targets_portfolio_id'))

    op.drop_table('allocation_targets')
    # ### end Alembic commands ###
