"""initial schema

Revision ID: 4f70dcca1811
Revises: 
Create Date: 2026-08-30 14:56:58.203425
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# Autogenerate renderiza las columnas monetarias como app.db.types.ExactNumeric
# y las de fecha como app.db.types.UtcDateTime, pero NO añade este import por
# su cuenta. Sin él, cualquier migración que toque esas columnas falla con
# NameError al ejecutarse.
import app.db.types  # noqa: F401

# El variant JSONB de PostgreSQL se renderiza como
# postgresql.JSONB(astext_type=Text()), con Text sin cualificar.
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql

revision: str = '4f70dcca1811'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('asset_type', sa.Enum('STOCK', 'ETF', 'ADR', 'REIT', 'FUND', 'CRYPTO', 'OTHER', name='asset_type', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('exchange', sa.String(length=30), nullable=True),
    sa.Column('sector', sa.String(length=80), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=60), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_verified_at', app.db.types.UtcDateTime(), nullable=True),
    sa.Column('created_at', app.db.types.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('length(currency) = 3', name=op.f('ck_assets_currency_iso')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets'))
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index('ix_assets_is_active', ['is_active'], unique=False)
        batch_op.create_index('ix_assets_sector', ['sector'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_symbol'), ['symbol'], unique=True)

    op.create_table('data_sync_state',
    sa.Column('id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), nullable=False),
    sa.Column('resource_type', sa.String(length=40), nullable=False),
    sa.Column('resource_key', sa.String(length=120), nullable=False),
    sa.Column('last_attempt_at', app.db.types.UtcDateTime(), nullable=True),
    sa.Column('last_success_at', app.db.types.UtcDateTime(), nullable=True),
    sa.Column('next_eligible_at', app.db.types.UtcDateTime(), nullable=True),
    sa.Column('ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_sync_state')),
    sa.UniqueConstraint('resource_type', 'resource_key', name='uq_data_sync_state_resource')
    )
    op.create_table('fx_rates',
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('quote_currency', sa.String(length=3), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rate', app.db.types.ExactNumeric(precision=24, scale=12), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('fetched_at', app.db.types.UtcDateTime(), nullable=False),
    sa.CheckConstraint('CAST(rate AS NUMERIC) > 0', name=op.f('ck_fx_rates_rate_positive')),
    sa.CheckConstraint('base_currency <> quote_currency', name=op.f('ck_fx_rates_distinct_currencies')),
    sa.CheckConstraint('length(base_currency) = 3', name=op.f('ck_fx_rates_base_currency_iso')),
    sa.CheckConstraint('length(quote_currency) = 3', name=op.f('ck_fx_rates_quote_currency_iso')),
    sa.PrimaryKeyConstraint('base_currency', 'quote_currency', 'date', name=op.f('pk_fx_rates'))
    )
    op.create_table('portfolios',
    sa.Column('id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.types.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('length(base_currency) = 3', name=op.f('ck_portfolios_base_currency_iso')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolios'))
    )
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolios_name'), ['name'], unique=True)

    op.create_table('asset_quotes',
    sa.Column('asset_id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('previous_close', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('quote_time', app.db.types.UtcDateTime(), nullable=True),
    sa.Column('fetched_at', app.db.types.UtcDateTime(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_quotes_asset_id_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id', name=op.f('pk_asset_quotes'))
    )
    op.create_table('fundamental_snapshots',
    sa.Column('id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), nullable=False),
    sa.Column('asset_id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('market_cap', app.db.types.ExactNumeric(precision=24, scale=2), nullable=True),
    sa.Column('trailing_pe', sa.Float(), nullable=True),
    sa.Column('forward_pe', sa.Float(), nullable=True),
    sa.Column('price_to_book', sa.Float(), nullable=True),
    sa.Column('price_to_sales', sa.Float(), nullable=True),
    sa.Column('ev_to_ebitda', sa.Float(), nullable=True),
    sa.Column('profit_margin', sa.Float(), nullable=True),
    sa.Column('return_on_equity', sa.Float(), nullable=True),
    sa.Column('debt_to_equity', sa.Float(), nullable=True),
    sa.Column('revenue_growth', sa.Float(), nullable=True),
    sa.Column('earnings_growth', sa.Float(), nullable=True),
    sa.Column('eps_trailing', sa.Float(), nullable=True),
    sa.Column('dividend_yield', sa.Float(), nullable=True),
    sa.Column('payout_ratio', sa.Float(), nullable=True),
    sa.Column('beta', sa.Float(), nullable=True),
    sa.Column('fifty_two_week_high', sa.Float(), nullable=True),
    sa.Column('fifty_two_week_low', sa.Float(), nullable=True),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('fetched_at', app.db.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_fundamental_snapshots_asset_id_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fundamental_snapshots')),
    sa.UniqueConstraint('asset_id', 'as_of', name='uq_fundamental_snapshots_asset_as_of')
    )
    with op.batch_alter_table('fundamental_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_fundamental_snapshots_asset_as_of', ['asset_id', 'as_of'], unique=False)

    op.create_table('price_history',
    sa.Column('asset_id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('adj_close', sa.Float(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('fetched_at', app.db.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_price_history_asset_id_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id', 'date', name=op.f('pk_price_history'))
    )
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index('ix_price_history_date', ['date'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), nullable=False),
    sa.Column('portfolio_id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), nullable=False),
    sa.Column('asset_id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), nullable=True),
    sa.Column('type', sa.Enum('BUY', 'SELL', 'DIVIDEND', 'DEPOSIT', 'WITHDRAWAL', 'FEE', 'SPLIT', name='transaction_type', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('executed_at', app.db.types.UtcDateTime(), nullable=False),
    sa.Column('quantity', app.db.types.ExactNumeric(precision=28, scale=10), nullable=True),
    sa.Column('price', app.db.types.ExactNumeric(precision=20, scale=8), nullable=True),
    sa.Column('cash_amount', app.db.types.ExactNumeric(precision=20, scale=8), nullable=True),
    sa.Column('fees', app.db.types.ExactNumeric(precision=20, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('fx_rate_to_base', app.db.types.ExactNumeric(precision=24, scale=12), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', app.db.types.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("type <> 'DIVIDEND' OR asset_id IS NOT NULL", name=op.f('ck_transactions_dividend_needs_asset')),
    sa.CheckConstraint("type NOT IN ('BUY','SELL') OR (  asset_id IS NOT NULL AND quantity IS NOT NULL  AND price IS NOT NULL AND cash_amount IS NULL)", name=op.f('ck_transactions_trade_payload')),
    sa.CheckConstraint("type NOT IN ('DEPOSIT','WITHDRAWAL') OR asset_id IS NULL", name=op.f('ck_transactions_cash_no_asset')),
    sa.CheckConstraint("type NOT IN ('DIVIDEND','DEPOSIT','WITHDRAWAL') OR (  cash_amount IS NOT NULL AND quantity IS NULL AND price IS NULL)", name=op.f('ck_transactions_cash_payload')),
    sa.CheckConstraint('CAST(fees AS NUMERIC) >= 0', name=op.f('ck_transactions_fees_non_negative')),
    sa.CheckConstraint('CAST(fx_rate_to_base AS NUMERIC) > 0', name=op.f('ck_transactions_fx_positive')),
    sa.CheckConstraint('cash_amount IS NULL OR CAST(cash_amount AS NUMERIC) > 0', name=op.f('ck_transactions_cash_positive')),
    sa.CheckConstraint('length(currency) = 3', name=op.f('ck_transactions_currency_iso')),
    sa.CheckConstraint('price IS NULL OR CAST(price AS NUMERIC) >= 0', name=op.f('ck_transactions_price_non_negative')),
    sa.CheckConstraint('quantity IS NULL OR CAST(quantity AS NUMERIC) > 0', name=op.f('ck_transactions_quantity_positive')),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_transactions_asset_id_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_transactions_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions')),
    sa.UniqueConstraint('portfolio_id', 'external_id', name='uq_transactions_external')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('ix_transactions_portfolio_asset_executed', ['portfolio_id', 'asset_id', 'executed_at'], unique=False)
        batch_op.create_index('ix_transactions_portfolio_executed', ['portfolio_id', 'executed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_transactions_portfolio_executed')
        batch_op.drop_index('ix_transactions_portfolio_asset_executed')

    op.drop_table('transactions')
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index('ix_price_history_date')

    op.drop_table('price_history')
    with op.batch_alter_table('fundamental_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_fundamental_snapshots_asset_as_of')

    op.drop_table('fundamental_snapshots')
    op.drop_table('asset_quotes')
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolios_name'))

    op.drop_table('portfolios')
    op.drop_table('fx_rates')
    op.drop_table('data_sync_state')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_symbol'))
        batch_op.drop_index('ix_assets_sector')
        batch_op.drop_index('ix_assets_is_active')

    op.drop_table('assets')
    # ### end Alembic commands ###
