"""perfil de fondo y clase declarada

Revision ID: 5036fc929ad2
Revises: 02f00629aa63
Create Date: 2026-09-21 10:42:35.140991
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# Autogenerate renderiza las columnas monetarias como app.db.types.ExactNumeric
# y las de fecha como app.db.types.UtcDateTime, pero NO añade este import por
# su cuenta. Sin él, cualquier migración que toque esas columnas falla con
# NameError al ejecutarse.
import app.db.types  # noqa: F401

# El variant JSONB de PostgreSQL se renderiza como
# postgresql.JSONB(astext_type=Text()), con Text sin cualificar.
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql

revision: str = '5036fc929ad2'
down_revision: str | None = '02f00629aa63'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fund_profiles',
    sa.Column('id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), nullable=False),
    sa.Column('asset_id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('legal_type', sa.String(length=60), nullable=True),
    sa.Column('stock_position', sa.Float(), nullable=True),
    sa.Column('bond_position', sa.Float(), nullable=True),
    sa.Column('cash_position', sa.Float(), nullable=True),
    sa.Column('other_position', sa.Float(), nullable=True),
    sa.Column('expense_ratio', sa.Float(), nullable=True),
    sa.Column('credit_ratings', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('fetched_at', app.db.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_fund_profiles_asset_id_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fund_profiles'))
    )
    with op.batch_alter_table('fund_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fund_profiles_asset_id'), ['asset_id'], unique=True)

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('declared_asset_class', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_column('declared_asset_class')

    with op.batch_alter_table('fund_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fund_profiles_asset_id'))

    op.drop_table('fund_profiles')
    # ### end Alembic commands ###
