"""foto semanal del ranking

Revision ID: 6fced7175482
Revises: 4dc3014a8333
Create Date: 2026-09-20 23:52:17.453288
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# Autogenerate renderiza las columnas monetarias como app.db.types.ExactNumeric
# y las de fecha como app.db.types.UtcDateTime, pero NO añade este import por
# su cuenta. Sin él, cualquier migración que toque esas columnas falla con
# NameError al ejecutarse.
import app.db.types  # noqa: F401

# El variant JSONB de PostgreSQL se renderiza como
# postgresql.JSONB(astext_type=Text()), con Text sin cualificar.
from sqlalchemy import Text  # noqa: F401


revision: str = '6fced7175482'
down_revision: str | None = '4dc3014a8333'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ranking_snapshots',
    sa.Column('id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), nullable=False),
    sa.Column('captured_on', sa.Date(), nullable=False),
    sa.Column('portfolio_id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('asset_class', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('grade', sa.String(length=16), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('class_size', sa.Integer(), nullable=False),
    sa.Column('available_signals', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('created_at', app.db.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_ranking_snapshots_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ranking_snapshots')),
    sa.UniqueConstraint('captured_on', 'portfolio_id', 'symbol', name='uq_ranking_snapshot')
    )
    with op.batch_alter_table('ranking_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ranking_snapshots_captured_on'), ['captured_on'], unique=False)
        batch_op.create_index('ix_ranking_snapshots_symbol_date', ['symbol', 'captured_on'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ranking_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_ranking_snapshots_symbol_date')
        batch_op.drop_index(batch_op.f('ix_ranking_snapshots_captured_on'))

    op.drop_table('ranking_snapshots')
    # ### end Alembic commands ###
