"""tasas de cdt por banco

Revision ID: a95025d5407a
Revises: 5036fc929ad2
Create Date: 2026-09-21 11:15:41.062638
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# Autogenerate renderiza las columnas monetarias como app.db.types.ExactNumeric
# y las de fecha como app.db.types.UtcDateTime, pero NO añade este import por
# su cuenta. Sin él, cualquier migración que toque esas columnas falla con
# NameError al ejecutarse.
import app.db.types  # noqa: F401

# El variant JSONB de PostgreSQL se renderiza como
# postgresql.JSONB(astext_type=Text()), con Text sin cualificar.
from sqlalchemy import Text  # noqa: F401


revision: str = 'a95025d5407a'
down_revision: str | None = '5036fc929ad2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cdt_offers',
    sa.Column('id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), nullable=False),
    sa.Column('entity', sa.String(length=120), nullable=False),
    sa.Column('term_label', sa.String(length=60), nullable=False),
    sa.Column('rate_pct', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('fetched_at', app.db.types.UtcDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cdt_offers')),
    sa.UniqueConstraint('entity', 'term_label', name='uq_cdt_offer_entity_term')
    )
    with op.batch_alter_table('cdt_offers', schema=None) as batch_op:
        batch_op.create_index('ix_cdt_offers_term', ['term_label'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cdt_offers', schema=None) as batch_op:
        batch_op.drop_index('ix_cdt_offers_term')

    op.drop_table('cdt_offers')
    # ### end Alembic commands ###
