"""journal entries

Revision ID: ae5068edce82
Revises: 320fcf27a88a
Create Date: 2026-09-20 19:38:57.382465
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# Autogenerate renderiza las columnas monetarias como app.db.types.ExactNumeric
# y las de fecha como app.db.types.UtcDateTime, pero NO añade este import por
# su cuenta. Sin él, cualquier migración que toque esas columnas falla con
# NameError al ejecutarse.
import app.db.types  # noqa: F401

# El variant JSONB de PostgreSQL se renderiza como
# postgresql.JSONB(astext_type=Text()), con Text sin cualificar.
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql

revision: str = 'ae5068edce82'
down_revision: str | None = '320fcf27a88a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), nullable=False),
    sa.Column('portfolio_id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), nullable=False),
    sa.Column('asset_id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), nullable=False),
    sa.Column('kind', sa.Enum('WATCH', 'BUY', 'HOLD', 'SELL', 'PASS', name='journal_kind', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('thesis', sa.Text(), nullable=False),
    sa.Column('invalidation', sa.Text(), nullable=True),
    sa.Column('invalidation_price', app.db.types.ExactNumeric(precision=20, scale=8), nullable=True),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('reviewed_at', app.db.types.UtcDateTime(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('snapshot_price', sa.Float(), nullable=True),
    sa.Column('snapshot_score', sa.Float(), nullable=True),
    sa.Column('snapshot_rank', sa.Integer(), nullable=True),
    sa.Column('snapshot_grade', sa.String(length=20), nullable=True),
    sa.Column('snapshot_verdict', sa.String(length=10), nullable=True),
    sa.Column('snapshot_flags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', app.db.types.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('length(trim(thesis)) > 0', name=op.f('ck_journal_entries_thesis_not_blank')),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_journal_entries_asset_id_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_journal_entries_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_entries'))
    )
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index('ix_journal_entries_asset', ['asset_id'], unique=False)
        batch_op.create_index('ix_journal_entries_portfolio_active', ['portfolio_id', 'is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_journal_entries_portfolio_active')
        batch_op.drop_index('ix_journal_entries_asset')

    op.drop_table('journal_entries')
    # ### end Alembic commands ###
